### ISSUE TITLE
Can't resolve 'stylus-loader'

### ISSUE THREAD

**Issue by lcxfs1991** [webpack-contrib/npm-install-webpack-plugin#110]
I have alread add stylus-loader config to webpack. When I require a stylus file, it successfully installed the dependencies, but it comes up with the following error:

![image](https://cloud.githubusercontent.com/assets/3348398/24861231/9262b1aa-1e2a-11e7-8e50-1e64490953aa.png)

When I restart the cmd, it works correctly.

**Comment by lcxfs1991** [comment]
I use happypack in my project, when I remove happypack config, it works correctly.

**Comment by alexander-akait** [comment]
Sorry plugin in `happypack`, also it no need for webpack v5, sorry for big delay, plugin will be live in near future
