### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by insin** [webpack-contrib/npm-install-webpack-plugin#122]
Error message when used with Webpack 4 beta 0:

```
path/to/npm-install-webpack-plugin/src/plugin.js:51
    compiler.resolvers.loader.plugin("module", this.resolveLoader.bind(this));
                              ^

TypeError: compiler.resolvers.loader.plugin is not a function
```

**Comment by hanxue** [comment]
My workaround is to temporarily disable the `NpmInstallPlugin`

```
new NpmInstallPlugin({
  save: true
}),
```
Will this issue be fixed before Webpack 4 becomes stable?

**Comment by insin** [comment]
Does this [Webpack 4 change](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202) mean the end of the plugin's current approach?

> ###Compiler
>
> While applying plugins `Compiler.options` is no longer accessible. Plugins should not access options. They should only depend on options passed to the plugin via constructor.

**Comment by skirankumar7** [comment]
please make this plugin works with web pack 4 also,
and also need a clear description that how this plugin works only after npm start or if I am code pulled from git and package.json has the new package added, during this webpack dev server is running will this plugin installs new package dependency or not.....
Please comment here 👍 ....

**Comment by marcofugaro** [comment]
RIP this plugin

**Comment by codeparl** [comment]
new NpmInstallPlugin({
  save: true
}),

This code doesn't work for  my webpack 4

**Comment by evilebottnawi** [comment]
Fixed

**Comment by jimblue** [comment]
Still have this issue

**Comment by zhishaofei3** [comment]
Still have this issue
