### ISSUE TITLE
What is smarterspam.com

### ISSUE THREAD

**Issue by zwhitchcox** [webpack-contrib/npm-install-webpack-plugin#126]
Side note, what is smarterspam.com? I looked online and couldn't find where the address pointed to anything.

**Comment by evilebottnawi** [comment]
Looks you have a virus, we don't use this url in code

**Comment by zwhitchcox** [comment]
https://github.com/webpack-contrib/npm-install-webpack-plugin/blob/master/package.json#L33

**Comment by evilebottnawi** [comment]
@zwhitchcox just email of contributor, some problems with plugin?
