### ISSUE TITLE
Not work at webpack@2.2.0-rc0

### ISSUE THREAD

**Issue by wssgcg1213** [webpack-contrib/npm-install-webpack-plugin#88]
```js
compiler.resolvers.normal.plugin("module", this.resolveModule.bind(this))
```

should be

```js
 compiler.plugin('compilation', (compilation) => {
  compilation.resolvers.normal.plugin("module", this.resolveModule.bind(this))
})
```

this works for me now.
  
I don't know whether the API will change again when the the official version webpack@2 is released.

**Comment by ericclemmons** [comment]
Thanks so much for troubleshooting this!  I'm on vacation now, but will merge this when I get back.

Awesome work @wssgcg1213 :) :) :)
