### ISSUE TITLE
Transfer project to https://github.com/webpack-contrib

### ISSUE THREAD

**Issue by ericclemmons** [webpack-contrib/npm-install-webpack-plugin#99]
@insin Howdy!

@bebraw contacted me about migrating this project to https://github.com/webpack-contrib, where "community" plugins could be maintained & shared.

Frankly, I'm all for building up the "webpack" brand and alleviating myself from being the face of projects like this.

If you agree, I think all we have to do is:

- Transfer this repo to that organization.
- Ensure @insin & I (@ericclemmons) are both contributors on that group.

**Comment by bebraw** [comment]
You both should have full access to the organization now. 👍

**Comment by insin** [comment]
Good stuff 🎉

**Comment by ericclemmons** [comment]
Done :)

> https://github.com/webpack-contrib/npm-install-webpack-plugin
